// This file was autogenerated by calcdeps.py
goog.addDependency("../../../closure-templates/soyutils.js", [], []);
goog.addDependency("../../../closure-templates/soyutils_usegoog.js", ['soy', 'soy.StringBuilder'], ['goog.dom', 'goog.format', 'goog.i18n.BidiFormatter', 'goog.i18n.bidi', 'goog.string', 'goog.string.StringBuffer']);
goog.addDependency("../../../pres4/hello.soy.js", ['example.templates'], ['soy', 'soy.StringBuilder']);
goog.addDependency("../../../pres4/hello.js", ['example'], ['example.templates', 'goog.dom']);
